export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER = 'LOAD_USER';
export const SAVE_SCROLL_STATUS = 'SAVE_SCROLL_STATUS';
export const SAVE_ACCOMPANY_SCROLL_STATUS = 'SAVE_ACCOMPANY_SCROLL_STATUS';
export const SAVE_SELL_SCROLL_STATUS = 'SAVE_SELL_SCROLL_STATUS';
